sudo: required
dist: xenial
services:
- docker
env:
  global:
  - IMAGE_NAME: "$TRAVIS_REPO_SLUG"
  - IMAGE_VERSION: "$TRAVIS_TAG"
  - secure: qRFcJ7nQEuXwM7Mhx+D9wXAk3G6jIyGvHjaaCySXUxLiEFU1zNucR9LDbiR8apVbUqQudDT9sj6qJU824/8mhTxQm8JlKxH35Hy2JQhhAAYEwS7WzbgZJtUoMP4Ew7GPiCRmWQ7OG3Nd4Ad/NxCQovVt1VMyEquBdIM5yNW9KLOHuop+ss2Rzh9kBuWgrHPoUBQAg0GkakrIPVACw8gbklr7e4nJR1XwDgdxyJAAEclpW6xSAJBsPO5T/Ps+7hpVdg6+huKvmg46YU9HQhJ3ec4UIgE6T4o2CDcwv5p/rDzf3nfAvJUQ+GjIJ6r6GD71fvk+Yxu/pohJCrZOpyi30i/L6vR3ixb+QgiIuoiM+DTX5oy82s91tFinbtnJK7D871vG3ADAHd0VZsbOTeT5Cs/vhcvzzoQ8h6U3Q7QVMLJSEmXcH/YAxjB3u1t8XMmawm+wJIweP3IxkjjchO6nyki1cPOrQ+b4x8oswvqDLKmDnCBuZpC9aQNBmMv6YSwS3DtpfDIsf1nArzG6Jm6lov/dCNMqVlQScq8Kd1rBlMekV0pU5MOzXrwamFNWeZgUnyeeXuXMpUEoGq3bhJ/0fMWf07Su2Zq88KwHyCs+TQeixpuFv8ppRwSyr5mtou0iynqLfP24SB+EIeGUShVceLMSkdUNwkNCxkv0/c7wDnM=
  - secure: fm4l8xJMFkz0+pTHKbmNDKlezeSGs6f/yKTHyBN3UE5c5W2/1ZlHUv2kyFiiJQ206QHtEh6QdRErb2pnlPVkc2Zo86dtB457J9mFNwD6EmHY0O4uHijMpOaKsqIixAzyAgovMM7X1LjEp4XHZHTV8PsgOE+ye5QAPlJwtmAKx9K1wNJeohFpZ+pROdB5bZKMaV35YEp4+UUKj4kx4OIt66ky48OEs0utTJJKhJrIei+4OqSTxrBMmt7THR9BXFV8XtoCcTCWl2Ck75CyaXlKzv1PmRy6splY5zK/JiVxzc6LN5sPCetqAxTXTlJpYP4yNINYvVh+zE7LSOsxpOZAkXNAcERstYxH5y26jgDL025Jt6EgWWiSQfik8F3IPKnrjN+rdtZLF3E17HKSRXHN3RjeSkw7eoulvJL8aOjd8TFSurebSTnksq+rWZXN/vl/wH6pjmwV7LGr7Bs2j1oOpjYNYnLDSB4xTM4moBQWV7jvepLUnW97WOQrBMawQKUq8GUt+5tvINr0+2kNRRcTuWiDA33Uv8ZL70UhrV7yVO25bY6dxVJ+IwVA5ut6QadkjLS7lfMOvyY7G/JW2wiMjYsd/tYlSxY9GdT/wi0LxSrgpGAykgbQkTci0Q/z4TzKYdEDyfSV0HCvkxUZKCR7Wj/AGvxh7rAlJNQwuurviDA=
language: python
python:
- '3.6'
install:
- pip install flake8
- pip install coveralls
script:
- flake8 .
- python setup.py test
after_success:
- coveralls
before_deploy:
- python setup.py bdist_wheel
deploy:
  matrix:
  - provider: pypi
    user: adalekin
    password:
      secure: MrESXRRxQu1lYQEqip3kg0SC21xp8T7lsLQL1PoNWDHhQqHzH87HDlKzkds3l+cnRPhbt6CMEvJckZLbQVq60Js8arfswBeyRSm72D5P2PR8/DhfAaLW0CbOEc2jtaBxuUi5b3ZpMDSQi7/nZEG4kXoxiv2fznYLqppb118B6/sD9+NHphYIxQYG/G9YW2eVpZmXEl33Ed+GUIuQTsQ6Frij0U7PlsC7Og/0sZd6pzEGFaCqA//EhlDw7V2BU6PqhzXHO9tiL0G9N51iAMlFuc4Vspnsfs92DGqvHYhbLN9QrhX0Fp+1lcxXYyOQJRnyBCXABIK2nzUeXJqONx8aVhNlkBu9eybMagQYhfdHdOWSjGAWgos1vBtR53ft7XN6bF7kZ4IpKmPJ6pWsQ9oOC/oP5TQbERK5UHV2aLYLY/Dl/LmyZl2j6FZUjuF4PJ3q03QJ05SpWHw0MDT9RhfsP7Tuo4FJ0J71u39IYBMOLj1leF8A82/FeaZjBqfvil86OSv1zO/cME8oH+pSXg4sHmUAan6QsvOfqEmd5jzpU3QAadQxdMfdLqIFc8j404swn0cdH7ydEM5dtKpPkkKEw1GBkyxR6HyQF8SF/dJHO9l8nrVT6mikn1ejW9ffZBBuIG3b2lLB1scLVcCr+lktP9TbJ/B4msuwikSW4K7Ji5Y=
    distributions: sdist bdist_wheel
    on:
      tags: true
      python: 3.6
after_deploy:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker build -t "${IMAGE_NAME}:${IMAGE_VERSION}" .
- docker push "${IMAGE_NAME}:${IMAGE_VERSION}"
