sudo: required
dist: xenial
services:
- docker
env:
  global:
  - IMAGE_NAME: "$TRAVIS_REPO_SLUG"
  - IMAGE_VERSION: "$TRAVIS_TAG"
  - secure: CgB4qDf1A27xpGLCACT3hjy2OccNMWtRWLQr+Qx6MuE1f/7o4IC3KgNCpQPmQhDJFPhS86GbL8WSTXtDxMCzkhxM9rrIgVP+aIXDq+i0dCHnIU1NySrgrA/LzQzoWKV7evJIJTwpsQFO6Js8zhJB30TWBj7fLp6J4l+YB4trWL+vpVHtGJHitDVYBa9soFtytj1Z83fhFA5gP+LSNXFZeTqHAfsLO87PeQJbhQZ6gwU7Wdn0xkRWUdnyN9bvU4GE6Kd2dZn56SKeZLcsHACMqCo7jXqY0mxGofvP9Tg1/YqFUG8BuDmO3QTDen1hcwbH7HBhzJT5AskXj/pahboPC/o9xv6SvnhfriwPrZZTj0AIi64LWqn6a6BheUH3026NnfG6CCu0pRkm5h5M+QsTi2b/1CX2kn+uqwmmarZTaA8PHCKmWv9xu5SogvdpPHfrw5iKrjEDW5vFraVkP0MNxsKLDRXnIASWvvD93BcBhdcRH+Y/FH06pXoQZ5xizTkwCpZwxuvi1/Bj8dsFsxtRSt8ivJjaUPqAdKnjf8+M0NNGVm3/fqWO27QPlpPGixaRVqainXrrIGvu6sV5UQ/4kvipQem3Caz9uVKftxyZwpj+1QeXw0kAJkKFeXLGcgs3r8GUA/7bU79xtFsZG/oDyKdlxZJcfezmPlIQH7Lj+ag=
  - secure: YqfhhImCWlescojO/QvxpTgw02BDRMqIb8e+1FKgWEk0GMvyFOts8DXltOd3EQlgrtWh54tKv7J3h0hUZxbe8mhCHccrK3dW0Z29ZhQuo+dQXnlm2nyFOGOxDU17KjuOOqLHpFBCpLf7HY6S+vnL7Fj+Sdxrl/yrQIDxOOPZYQqx3mUmEklR7aRJB7KeIrXYiOj1GKmzYa8LC2y22bLMyR2ik9JafwxLv01xYWSRb1XBwDblB3xzNnV/psxMPPTpW4HdVatdwfHiSsZfIp4OG64uOg91L34893mnnNDDP+wzI/mi2mnhF+opNjPEAbfgriTpwQkOZ3cmfoHJXH3LU7qTT6gC8tGmFuTDNHFiOW0m13rJFReC+3GepbgMU6+VzvKH/Ofi86fTh7KBufmsFP7WDsxsICaKK+LCs4SxSD0ZI3RHM/+rSOES5aK1P461p0FGrTnEG/9dWjbwSuQnsR3ABDPApRMW6lmPNKlS3eks14kKLuTHyQUMRXcTPxBY2/OYemQRFNavorvK202yAqxdz+rVPWa8Qt5waN+iqRFobOt7ft8L3qDND1khCTWaCIPTk13s5FlVwAEQ6mQ5xy5flOyyIdgf/h24OhZtiMwrl3zll1ASiBJonBMOPqzvG3pBfhrUovNkR7tLrrilTl70qLnD0gD9IAfHv8wUimI=
language: python
python:
- '3.6'
install:
- pip install flake8
- pip install coveralls
script:
- flake8 .
- python setup.py test
after_success:
- coveralls
before_deploy:
- python setup.py bdist_wheel
deploy:
  provider: pypi
  user: adalekin
  password:
    secure: ZQo8ZPvrtiOO2d41siQNGF1qKHh3qz4AQYkxvTIElMIiN2KNBQ7ENLM/MX6Hlo1TfoxOta6UUDIQhrhLVYPKPLajOHvWtjwQgZdZR3Re2XsErO9fyVZfhB3VAhe5KeDwD5HvGAS2dcESSUH6JJ+zWs5+zdKWbDxMEtTB0LU1FkvOtubh9oxPaxG19L476gahfbT/EQJsOzDxRZQvNdt4IJVreyokLL+oqjNmWXyWWYatDgHvlhJjwHbv8stzE+uc59WoyeUwv0lNm9YhpNvI7SPenSHllRfqK3B5eDgjNeeBvRDvX9mvy6Qf4CRT3W2WqUSCbXNrH134EWYlBjmiDG3Y5X2fTor8AVdqFzu2Qer39C238XKo5uD5VCjU5D1hfmrGMowQClhYTUdkobw+TGjygFMqbU6g9MYuZUod5llVvSelZSQeckACZmL2XmQ68Q3TS1mLWYT6QHIJ1GIk1sbMekmL2mF27OBiz6tPhlF1k8N/OmzbKXTniX6/9edyRoPNRcZB3FZvenCFVTj+MhlPL78xlqXJeZ5+KwaDUQU33dSL0mn7hRGw7d3WZs+FjWSEdsGT8Y1EDH3a3i1szA9rH7mahJ3tePvIQ+KIm7/bwhNmVgNnNJDpSV/Wm7WF5vEd/srkxjizQxhz4AfsQgW3jzLwHKn6zjrry7orkmo=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6
after_deploy:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker build -t "${IMAGE_NAME}:${IMAGE_VERSION}" .
- docker push "${IMAGE_NAME}:${IMAGE_VERSION}"
